using System;
using System.Collections.Generic;
using System.Text;

namespace lectorArchivo.Transversal
{
    public enum Categoria
    {
        ESPACIO, LETRA_A, LETRA_B, LETRA_C, LETRA_D, LETRA_E, LETRA_F, LETRA_G, LETRA_H, LETRA_I,
        LETRA_J, LETRA_K, LETRA_L, LETRA_M, LETRA_N, LETRA_O, LETRA_P, LETRA_Q, LETRA_R, LETRA_S,
        LETRA_T, LETRA_U, LETRA_V, LETRA_W, LETRA_X, LETRA_Y, LETRA_Z, LETRA_TILDE_A, LETRA_TILDE_E,
        LETRA_ENYE, LETRA_TILDE_O, PUNTO, COMA, INTERROGACION_CIERRA, INTERROGACION_ABRE, COMILLA_SIMPLE,
        ADMIRACION_CIERRA, ADMIRACION_ABRE, PARENTESIS_CIERRA, PARENTESIS_ABRE, LETRA_ET, DOS_PUNTOS,
        PUNTO_Y_COMA, IGUAL, MAS, GUION, GUION_BAJO, COMILLAS_DOBLES, SIGNO_PESOS, ARROBA, NUMERO_CERO,
        NUMERO_UNO, NUMERO_DOS, NUMERO_TRES, NUMERO_CUATRO, NUMERO_CINCO, NUMERO_SEIS, NUMERO_SIETE, NUMERO_OCHO,
        NUMERO_NUEVE,BARRA_INCLINADA,

        ERROR,FIN_DE_ARCHIVO,


        LETRA_MORSE, PREGUNTA_ABRE_MORSE, PREGUNTA_CIERRA_MORSE, COMILLA_SIMPLE_MORSE, ADMIRACION_ABRE_MORSE,
        ADMIRACION_CIERRA_MORSE, BARRA_INCLINADA_MORSE, PARENTESIS_ABRE_MORSE, PARENTESIS_CIERRA_MORSE, ET_MORSE,
        DOS_PUNTOS_MORSE, PUNTO_Y_COMA_MORSE, IGUAL_MORSE, MAS_MORSE, GUION_MORSE, BARRA_BAJA_MORSE, COMILLAS_DOBLES_MORSE,
        SIGNO_PESOS_MORSE, ARROBA_MORSE, NUMERO_MORSE, ESPACIO_MORSE, TILDE_A_MORSE, TILDE_E_MORSE, TILDE_O_MORSE,
        LETRA_ENYE_MORSE, PUNTO_MORSE, COMA_MORSE, GUION_BAJO_MORSE
    }
}
